
import React, { useState, useMemo, useCallback } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Slider } from "@/components/ui/slider";
import { Calculator, Download, Share2 } from "lucide-react";
import { toast } from "sonner";

interface BudgetItem {
  category: string;
  percentage: number;
  amount: number;
  color: string;
}

const BudgetCalculator = () => {
  const [totalBudget, setTotalBudget] = useState(500000);
  const [guestCount, setGuestCount] = useState(200);
  
  const budgetCategories: Omit<BudgetItem, 'amount'>[] = [
    { category: "Venue", percentage: 35, color: "#FF6B9D" },
    { category: "Catering", percentage: 25, color: "#4ECDC4" },
    { category: "Photography", percentage: 15, color: "#45B7D1" },
    { category: "Decoration", percentage: 10, color: "#96CEB4" },
    { category: "Bridal Wear", percentage: 8, color: "#FFEAA7" },
    { category: "Music & Entertainment", percentage: 5, color: "#DDA0DD" },
    { category: "Miscellaneous", percentage: 2, color: "#98D8C8" }
  ];

  // Real-time calculation with useMemo for performance
  const calculatedBudget = useMemo(() => {
    return budgetCategories.map(item => ({
      ...item,
      amount: Math.round((totalBudget * item.percentage) / 100)
    }));
  }, [totalBudget]);

  // Real-time per person cost calculation
  const perPersonCost = useMemo(() => {
    return guestCount > 0 ? Math.round(totalBudget / guestCount) : 0;
  }, [totalBudget, guestCount]);

  // Optimized handlers with useCallback
  const handleTotalBudgetChange = useCallback((value: string) => {
    const numValue = parseInt(value) || 0;
    if (numValue >= 0 && numValue <= 10000000) {
      setTotalBudget(numValue);
    }
  }, []);

  const handleGuestCountChange = useCallback((value: string) => {
    const numValue = parseInt(value) || 1;
    if (numValue >= 1 && numValue <= 5000) {
      setGuestCount(numValue);
    }
  }, []);

  const handleSliderBudgetChange = useCallback((value: number[]) => {
    setTotalBudget(value[0]);
  }, []);

  const handleSliderGuestChange = useCallback((value: number[]) => {
    setGuestCount(value[0]);
  }, []);

  // Enhanced download functionality
  const handleDownloadBudget = useCallback(async () => {
    try {
      const budgetData = calculatedBudget.map(item => 
        `${item.category}: ₹${item.amount.toLocaleString('en-IN')} (${item.percentage}%)`
      ).join('\n');
      
      const content = `Wedding Budget Breakdown
==========================================
Total Budget: ₹${totalBudget.toLocaleString('en-IN')}
Guest Count: ${guestCount}
Cost per Person: ₹${perPersonCost.toLocaleString('en-IN')}

Detailed Breakdown:
${budgetData}

Generated by ShaadiSaathi Budget Calculator
Date: ${new Date().toLocaleDateString('en-IN')}
Time: ${new Date().toLocaleTimeString('en-IN')}`;
      
      const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `wedding-budget-${new Date().toISOString().split('T')[0]}.txt`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      
      toast.success("Budget breakdown downloaded successfully!");
    } catch (error) {
      console.error('Download error:', error);
      toast.error("Failed to download budget. Please try again.");
    }
  }, [calculatedBudget, totalBudget, guestCount, perPersonCost]);

  // Enhanced share functionality
  const handleShareBudget = useCallback(async () => {
    const shareText = `🎉 My Wedding Budget Planning 🎉
Total Budget: ₹${totalBudget.toLocaleString('en-IN')}
Guests: ${guestCount}
Cost per Person: ₹${perPersonCost.toLocaleString('en-IN')}

Top Categories:
• Venue: ₹${calculatedBudget[0]?.amount.toLocaleString('en-IN')} (${calculatedBudget[0]?.percentage}%)
• Catering: ₹${calculatedBudget[1]?.amount.toLocaleString('en-IN')} (${calculatedBudget[1]?.percentage}%)
• Photography: ₹${calculatedBudget[2]?.amount.toLocaleString('en-IN')} (${calculatedBudget[2]?.percentage}%)

Planned with ShaadiSaathi 💕`;
    
    try {
      if (navigator.share && navigator.canShare && navigator.canShare({ text: shareText })) {
        await navigator.share({
          title: 'My Wedding Budget',
          text: shareText,
          url: window.location.href
        });
        toast.success("Budget shared successfully!");
      } else if (navigator.clipboard) {
        await navigator.clipboard.writeText(shareText);
        toast.success("Budget details copied to clipboard!");
      } else {
        // Fallback for older browsers
        const textArea = document.createElement('textarea');
        textArea.value = shareText;
        document.body.appendChild(textArea);
        textArea.select();
        document.execCommand('copy');
        document.body.removeChild(textArea);
        toast.success("Budget details copied to clipboard!");
      }
    } catch (error) {
      console.error('Share error:', error);
      toast.error("Failed to share budget. Please try again.");
    }
  }, [totalBudget, guestCount, perPersonCost, calculatedBudget]);

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center text-2xl font-heading">
            <Calculator className="mr-2 h-6 w-6 text-wedding-pink" />
            Wedding Budget Calculator
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-4">
              <div>
                <Label htmlFor="totalBudget">Total Budget (₹)</Label>
                <Input
                  id="totalBudget"
                  type="number"
                  value={totalBudget}
                  onChange={(e) => handleTotalBudgetChange(e.target.value)}
                  className="mt-1"
                  min="0"
                  max="10000000"
                  step="10000"
                  placeholder="Enter your budget"
                />
                <div className="mt-3">
                  <Slider
                    value={[totalBudget]}
                    onValueChange={handleSliderBudgetChange}
                    max={2000000}
                    min={50000}
                    step={25000}
                    className="w-full"
                  />
                  <div className="flex justify-between text-xs text-gray-500 mt-1">
                    <span>₹50K</span>
                    <span>₹20L+</span>
                  </div>
                </div>
              </div>
              
              <div>
                <Label htmlFor="guestCount">Number of Guests</Label>
                <Input
                  id="guestCount"
                  type="number"
                  value={guestCount}
                  onChange={(e) => handleGuestCountChange(e.target.value)}
                  className="mt-1"
                  min="1"
                  max="5000"
                  step="1"
                  placeholder="Enter guest count"
                />
                <div className="mt-3">
                  <Slider
                    value={[guestCount]}
                    onValueChange={handleSliderGuestChange}
                    max={1000}
                    min={25}
                    step={5}
                    className="w-full"
                  />
                  <div className="flex justify-between text-xs text-gray-500 mt-1">
                    <span>25</span>
                    <span>1000+</span>
                  </div>
                </div>
              </div>
              
              <div className="p-4 bg-wedding-cream/50 rounded-lg border">
                <h4 className="font-semibold text-wedding-navy mb-3">Budget Summary</h4>
                <div className="space-y-2 text-sm">
                  <div className="flex justify-between">
                    <span>Total Budget:</span>
                    <span className="font-semibold">₹{totalBudget.toLocaleString('en-IN')}</span>
                  </div>
                  <div className="flex justify-between">
                    <span>Guests:</span>
                    <span className="font-semibold">{guestCount}</span>
                  </div>
                  <div className="flex justify-between border-t pt-2">
                    <span>Cost per Person:</span>
                    <span className="font-semibold text-wedding-pink">₹{perPersonCost.toLocaleString('en-IN')}</span>
                  </div>
                </div>
              </div>
            </div>
            
            <div className="space-y-3">
              <h4 className="font-semibold text-lg">Budget Breakdown</h4>
              <div className="space-y-2 max-h-80 overflow-y-auto">
                {calculatedBudget.map((item, index) => (
                  <div key={index} className="flex items-center justify-between p-3 border rounded-lg hover:bg-gray-50 transition-colors">
                    <div className="flex items-center space-x-3">
                      <div 
                        className="w-4 h-4 rounded-full flex-shrink-0" 
                        style={{ backgroundColor: item.color }}
                      />
                      <span className="font-medium text-sm">{item.category}</span>
                    </div>
                    <div className="text-right">
                      <div className="font-semibold text-sm">₹{item.amount.toLocaleString('en-IN')}</div>
                      <div className="text-xs text-gray-500">{item.percentage}%</div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
          
          <div className="flex flex-col sm:flex-row gap-3 pt-4 border-t">
            <Button 
              onClick={handleDownloadBudget}
              className="bg-wedding-navy hover:bg-wedding-navy/90 flex-1"
            >
              <Download className="w-4 h-4 mr-2" />
              Download Budget
            </Button>
            <Button 
              onClick={handleShareBudget}
              variant="outline"
              className="border-wedding-pink text-wedding-pink hover:bg-wedding-pink/10 flex-1"
            >
              <Share2 className="w-4 h-4 mr-2" />
              Share Budget
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default BudgetCalculator;
